### ISSUE TITLE
Add the design files

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tftshop#4]

**Comment by VonSub** [comment]
used fonts: 

Lorem ipsum copy: Nunito Sans Semibold
Button Titles : Open Sans Semibold
Buttons : Open Sans 
![desktop hd copy](https://user-images.githubusercontent.com/29431263/50980635-7c84c900-14f9-11e9-8ad7-d1b26ba9cfc1.png)
![desktop hd copy 7](https://user-images.githubusercontent.com/29431263/50980636-7d1d5f80-14f9-11e9-9323-c59b7f254b16.png)
![desktop hd](https://user-images.githubusercontent.com/29431263/50980638-7d1d5f80-14f9-11e9-9e32-06f24729e342.png)
